# services:
#   app:
#     build:
#       context: .
#     ports:
#       - "8000:8000"  # Allows you to access the app from Windows
#     environment:
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
#       - DB_PASSWORD_PATH=/run/secrets/db_pw
#       - DB_HOST=db
#       - DB_PORT=5432
#       - DEBUG=True
#     tty: true
#     stdin_open: true

#     depends_on:
#       db:
#         condition: service_healthy
#     secrets:
#       - db_pw
#   db:
#     image: postgres:18
#     restart: always
#     secrets:
#       - db_pw
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=${POSTGRES_DB_NAME}
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db_pw
#     ports:
#       - "5432:${DB_PORT}"  # Allows pgAdmin/DBeaver on Windows to connect
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db_pw:
#     file: ./secrets/db_password.txt

services:
  app:
    build:
      context: .
    tty: true
    stdin_open: true
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db_pw
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=${DEBUG}

  db:
    image: postgres:18
    restart: always
    secrets:
      - db_pw
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_pw
    ports:
      - "5432:${DB_PORT}"  # Allows pgAdmin/DBeaver on Windows to connect
    healthcheck:
      # Use $$ to tell Docker to evaluate the variable inside the container
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

# Root-level definitions (must not be indented)
secrets:
  db_pw:
    file: ./run/secrets/db_password.txt

volumes:
  db-data: